Remove regions and enable commands from console and some related fixes
ObsidianMC/Obsidian pull request #152
Opened 2021-10-15 22:53 UTC by Czompi

## Remove regions and enable commands from console and some related fixes

- [x] Remove regions from MainCommandModule (72dc2a8a5fbe465e0bf8edbd9187bc87991846d5)
*I might know who added them* 😅
- [x] Grant all permissions to the console (b1737ca6aeb41ceef1bddfcea6f1373eefc5c0fe).
- [x] Enabled most of the commands to be executed from console (05439e7898ea2ccdc1311b9ac86439bd3bd4e1c2).

Ps.: Sorry for the lot of merges in this PR.

2021-10-15 22:56 UTC, Seb-stian commented
> Sorry for the lot of merges in this PR.

We can squash it to keep git history clean. No problem.

2021-10-16 00:21 UTC, Craftplacer requested changes

2021-10-16 00:21 UTC, Craftplacer commented on Obsidian/Commands/MainCommandModule.cs
> +        [IssuerScope(CommandIssuers.Any)]
This is common theme I've seen by people writing code here recently -- you're all too *explicit* with attributes.

Using no `IssuerScopeAttribute` should always default to all scopes. Please change it that when no attribute is provided it falls back to `Any` and delete the "unnecessary" lines.

Anyway, the rest of the PR looks fine though.

2021-10-16 00:37 UTC, Craftplacer approved these changes

2021-10-16 00:41 UTC, Czompi commented on Obsidian/Commands/Framework/CommandHandler.cs
> +            var issuers = m.GetCustomAttribute<IssuerScopeAttribute>()?.Issuers ?? CommandIssuers.Any;
May I add an internal `DefaultIssuerScope` field and use that instead of `CommandIssuers.Any`?

2021-10-16 00:43 UTC, Craftplacer commented on Obsidian/Commands/Framework/CommandHandler.cs
> +            var issuers = m.GetCustomAttribute<IssuerScopeAttribute>()?.Issuers ?? CommandIssuers.Any;
A constant value can be used to ensure consistency, sure.

2021-10-18 12:09 UTC, Naamloos approved these changes
Looks fine to me, great job

2021-10-18 12:10 UTC, merged