Feature/1.18 chunks update
ObsidianMC/Obsidian pull request #189
Opened 2021-12-07 08:59 UTC by Tides

This is for you guys to review and comment on the changes I made to adapt to the new 1.18 format and for it to be used in previous versions as well

2021-12-07 22:00 UTC, Jonpro03 commented on Obsidian/ChunkData/BiomeContainer.cs
> +        y %= 16;
C# does modulo on negatives differently than Java. You'll want to use NumericHelpers.Modulo here if you expect y will ever be negative.

2021-12-08 02:46 UTC, Tides commented on Obsidian/ChunkData/BiomeContainer.cs
> +        y %= 16;
👍🏼

2021-12-09 04:43 UTC, Craftplacer requested changes
Looks ok, but a bit more usage of Indexers could be cool.

2021-12-09 04:43 UTC, Craftplacer commented on Obsidian/ChunkData/BiomeContainer.cs
>      }
Implement https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/indexers/

2021-12-09 04:43 UTC, Craftplacer commented on Obsidian/ChunkData/BlockStateContainer.cs
>      }
Same as previous comment

2021-12-15 23:38 UTC, merged