Rewrite KeepAlive logic to be more in line with the Notchian server.
ObsidianMC/Obsidian pull request #294
Opened 2022-10-16 22:26 UTC by Naamloos

This PR would close #291.

2022-10-16 23:22 UTC, Tides requested changes
We should make a config value to set the keep alive timeout and pass it down to the client so people can configure it. Beside that LGTM ~

2022-10-16 23:29 UTC, Naamloos commented
To whoever decides to do the second review: please wait before merging, I want to add the config value(s).

2022-10-16 23:57 UTC, Craftplacer submitted a review, later dismissed

2022-10-16 23:57 UTC, Craftplacer commented on Obsidian/Client.cs
> +        if (missedKeepAlives.Any(x => keepAliveId - x > 30000)) // magic number is 30s in millis
small code style suggestion: use 30_000 instead of 30000, in order to make it more readable

2022-10-16 23:57 UTC, Craftplacer commented on Obsidian/Server.cs
> +                if (keepAliveTicks > 200) // to clarify: one tick is 50 milliseconds. 50 * 200 = 10000 millis means 10 seconds
Make this magic number is a constant field perhaps? (comment could be moved alongside it)

2022-10-17 07:19 UTC, Naamloos commented
Requested changes were made. Asking for re-review

2022-10-17 07:23 UTC, Tides approved these changes

2022-10-17 11:12 UTC, Craftplacer approved these changes

2022-10-17 11:12 UTC, merged