implement fix for tree generator
ObsidianMC/Obsidian pull request #352
Opened 2023-05-26 19:31 UTC by InFTord

fixes that one oak block that appears on top of tree 
@Jonpro03

2023-05-26 20:32 UTC, Jonpro03 requested changes

2023-05-26 20:32 UTC, Jonpro03 commented on Obsidian/WorldData/Generators/Overworld/Features/Trees/BaseTree.cs
> +                        await helper.SetBlockAsync(origin.X + xx, trunkHeight + origin.Y + heightOffset, origin.Z + zz,
Surely it's the case that the other leaf blocks need to account for `heightOffset` too, right?

2023-05-27 14:35 UTC, Jonpro03 approved these changes, later dismissed
LGTM

2023-05-27 14:50 UTC, Jonpro03 submitted a review, later dismissed

2023-05-28 02:20 UTC, Tides approved these changes

2023-05-28 17:21 UTC, Jonpro03 approved these changes

2023-05-28 17:21 UTC, merged