Server refactor
ObsidianMC/Obsidian pull request #403
Opened 2023-11-18 06:53 UTC by Tides

This is a refactoring of Server, WorldManager and packet broadcasting. Abstracting them out further and removing a lot of circular dependencies.

Notable Changes:
- WorldManager is now a hosted service. It will load or generate specified worlds right after the server itself is started and also manage every loaded world chunk on its own loop. Note that this doesn't tick worlds, as that still handled within the main server loop

- Packet broadcasting is no longer handled by the server class and is now handled by the [PacketBroadcaster](https://github.com/ObsidianMC/Obsidian/blob/server-refactor/Obsidian/Services/PacketBroadcaster.cs) class & registered as a hosted service as well for priority queuing & sending packets. There are methods to skip the queue and directly send packets to clients if needed. This is the first iteration and needs more discussion.

- Entities no longer depend directly on the server to broadcast packets & will inherit the packet broadcaster service from their respective worlds. With this change, we'll have to implement more methods to do specific things (like rotating an entity's head) and not do any packet broadcasting outside of the entity class and serverbound packets.

I planned to also include the plugin manager refactor here but its as big as these first couple changes so I left it out (#377) ~

I believe these changes are pushing the server further to be more clean and concise while tackling (#185). The end goal is to depend more on Microsoft's hosting extensions and not be overwhelmed overall.

2023-11-18 15:28 UTC, Craftplacer submitted a review, later dismissed

2023-11-20 21:32 UTC, Jonpro03 requested changes
Refreshing server status during initial world gen causes a crash

2023-11-20 21:45 UTC, Jonpro03 reviewed
Crash when loading a world from disk
EDIT: nvm... seems fine after a clean

2023-11-21 09:59 UTC, Tides commented
> Crash when loading a world from disk EDIT: nvm... seems fine after a clean

:eyes:

2023-11-21 14:25 UTC, Naamloos commented
> Crash when loading a world from disk EDIT: nvm... seems fine after a clean

Average obsidian update experience

2023-11-22 23:07 UTC, Naamloos approved these changes, later dismissed

2023-11-22 23:08 UTC, Naamloos commented
I was not aware of priorityqueue being a thing, cool!

2023-11-23 17:00 UTC, inftord commented on Obsidian.API/_Interfaces/IServerConfiguration.cs
> +    public int PregenerateChunkRange { get; set; }
probably we should document all fields here, what do yall think?

2023-11-23 17:00 UTC, InFTord commented on Obsidian/Utilities/Extensions.cs
> +        var b = new System.Numerics.BigInteger(hash);
why

2023-11-24 17:52 UTC, merged