Fixes #251 & #418
ObsidianMC/Obsidian pull request #420
Opened 2024-01-21 22:50 UTC by StarlkYT

*(I dunno how I can separate each commit to a different PR)*

2024-01-21 23:00 UTC, Tides requested changes

2024-01-21 23:00 UTC, Tides commented on Obsidian/Server.cs
> +                if (!_isFullyInitialized)
You can use WorldManager.ReadyToJoin

2024-01-21 23:10 UTC, Naamloos commented
420 blaze it

2024-01-21 23:11 UTC, Naamloos requested changes
Apart from tides' requested change this looks fine

2024-01-21 23:24 UTC, StarlkYT commented on Obsidian/Server.cs
> +                if (!_isFullyInitialized)
Should be good now 😄

2024-01-22 05:57 UTC, Craftplacer approved these changes

2024-01-22 15:12 UTC, merged