Fixes #426
ObsidianMC/Obsidian pull request #428
Opened 2024-02-21 21:36 UTC by TheVeryStarlk

2024-02-22 01:00 UTC, Jonpro03 requested changes
🙏

2024-02-22 01:00 UTC, Jonpro03 commented on Obsidian/Client.cs
> +        await Player.UpdateChunksAsync(distance: server.Configuration.ViewDistance);
The initial load MUST be 7 radius, or the client will time out waiting / spam log about too many chunks
(Soon this changes to 3 I think...)

ref:
https://wiki.vg/Protocol_FAQ#.E2.80.A6all_connecting_clients_spasm_and_jerk_uncontrollably.21

2024-02-22 12:29 UTC, TheVeryStarlk commented on Obsidian/Client.cs
> +        await Player.UpdateChunksAsync(distance: server.Configuration.ViewDistance);
Oh right, completely forgot that. Interesting that I tested it on my client, and it worked. Should be good now.

2024-02-22 22:05 UTC, Naamloos commented on Obsidian/Utilities/ServerConfiguration.cs
> +        set => viewDistance = value >= 3 ? value : viewDistance;
since viewDistance is 10 by default, why when it is 1 or 2, set it to 10? wouldn't 3 be a more sensible default here?

2024-02-22 22:05 UTC, Naamloos commented on Obsidian/Utilities/ServerConfiguration.cs
> +        set => viewDistance = value >= 3 ? value : viewDistance;
or lower*

2024-02-23 01:49 UTC, TheVeryStarlk commented on Obsidian/Utilities/ServerConfiguration.cs
> +        set => viewDistance = value >= 3 ? value : viewDistance;
Oh yes, you're completely right. However, settings it to anything less than 3 will cause weird artifacts.

2024-02-23 01:50 UTC, TheVeryStarlk commented on Obsidian/Utilities/ServerConfiguration.cs
> +        set => viewDistance = value >= 3 ? value : viewDistance;
Should be good now.

2024-02-23 02:28 UTC, Craftplacer submitted a review, later dismissed

2024-02-23 02:28 UTC, Craftplacer commented on Obsidian/Utilities/ServerConfiguration.cs
> +        set => viewDistance = value >= 3 ? value : (byte) 3;
Consider a const variable for 3

2024-02-23 09:41 UTC, Naamloos approved these changes, later dismissed

2024-02-23 15:31 UTC, TheVeryStarlk commented on Obsidian/Utilities/ServerConfiguration.cs
> +        set => viewDistance = value >= 3 ? value : (byte) 3;
Good idea.

2024-02-23 16:55 UTC, Naamloos approved these changes

2024-02-23 19:01 UTC, Naamloos commented
Just gonna go ahead and merge this since all issues have been resolved and this looks fine now

2024-02-23 19:01 UTC, merged