Implement player abilities packet
ObsidianMC/Obsidian pull request #433
Opened 2024-02-27 21:32 UTC by TheVeryStarlk

2024-02-28 04:17 UTC, Craftplacer submitted a review, later dismissed
Looks fine, but doesn't seem possible to update after first packet has been sent.

2024-02-28 18:50 UTC, TheVeryStarlk commented
> Looks fine, but doesn't seem possible to update after first packet has been sent.

Yes because apparently the server should send [this instead](https://wiki.vg/Protocol#Update_Attributes)

2024-03-05 23:56 UTC, Tides requested changes
🙏🏼

2024-03-05 23:56 UTC, Tides commented on Obsidian.API/_Types/PlayerAbility.cs
> +﻿namespace Obsidian.API._Types;
Before I merge fix pls

2024-03-06 00:05 UTC, TheVeryStarlk commented on Obsidian.API/_Types/PlayerAbility.cs
> +﻿namespace Obsidian.API._Types;
Good now?

2024-03-06 00:07 UTC, merged