Expose MinecraftStream
ObsidianMC/Obsidian pull request #441
Opened 2024-06-23 14:20 UTC by Tides

As the title states, this is to give developers a way to write/read packet data. An example would be through plugin messages or the new ItemComponents introduced in 1.21.

2024-06-23 18:10 UTC, Craftplacer requested changes
LGTM, but check my comment

2024-06-23 18:10 UTC, Craftplacer commented on Obsidian.API/_Interfaces/INetSteamReader.cs
> +public interface INetSteamReader : INetStream
Sir, we are not a games distribution platform.

2024-06-23 18:11 UTC, Tides commented on Obsidian.API/_Interfaces/INetSteamReader.cs
> +public interface INetSteamReader : INetStream
LOL will fix 😭

2024-06-24 11:13 UTC, Craftplacer approved these changes

2024-06-24 11:13 UTC, merged